### ISSUE TITLE
How to fix problem with ver 2.8+ [ vcredist 2015 ]

### ISSUE THREAD

**Issue by po456asd** [Masuzu/GBFPokerBot#106]
while 2.7 work fine i can't even open ver 2.8
and can't reinstall vcredist 2015 too
it got 0x80240017 error tho

https://drive.google.com/open?id=0B4AQ7NyN6b_VOWx3UDVRRkx6REk

**Comment by po456asd** [comment]
okay, it i read on many website it appraed that my computer not use window7 sp 1 so i need to fix by install sp1 to computer (not sure) (i'll test and edit this issues again)

in case you want to try 
you can download it here
https://www.microsoft.com/en-us/download/details.aspx?id=5842

use
7601.17514.101119-1850_Update_Sp_Wave1-GRMSP1.1_DVD.iso
mount it to your computer and install it then try to reinstall vcredist 2015 again

**Comment by Omegawp** [comment]
Mine still not working. I tried to install from that ISO and it said I already install it. But I still have the same problems as yours.

**Comment by po456asd** [comment]
@Omegawp hey, but mine worked!
after installed sp1, i reinstall vcredist 2015 here and restart the computer.
https://www.microsoft.com/en-us/download/details.aspx?id=48145

and it just worked.
![image](https://cloud.githubusercontent.com/assets/13596788/24786265/4f5596fe-1b8a-11e7-9ac2-28257b3e6882.png)

**Comment by Omegawp** [comment]
I'm SP1 now but still stuck at installing Visual C++ with 0x80070424 error. I tried troubleshoot but got nothing... Maybe I should give up my subcribe this month ;w;

**Comment by po456asd** [comment]
what windows that you use?

**Comment by Masuzu** [comment]
@Omegawp You can still use the previous version 2.7.0 and skip the version check window by closing it.
The error related to the intallation of VC++ 2015 redistributable packages that you have should be linked to missing Windows Updates.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/b1589508-91ec-4989-bbfc-8ec43321c35a/vc-2015-redistributable-cannot-install-due-to-windows-update?forum=vssetup

**Comment by Omegawp** [comment]
Ohhhhhh Thank you so much. Mazaru. I saw it said about missing key so I thought I need to use only new version.

About my Windows update, I googled and tried so many ways. (Your link included) I think I need to reinstall my Windows but I cannot do it now.

By the way. How long can I use 2.7 version? In case I cannot fix my Windows issue.

**Comment by po456asd** [comment]
till the end of the galaxy.
jk, till he change a subscribed method.

**Comment by Masuzu** [comment]
@Omegawp The version 2.7 won't be deprecated any time soon so you're safe to use it for as long as you'd like. Should you have a stable internet connection and a computer which can run GBF smoothly (no frame stuttering/delays with animations), you should never encounter the bug which was fixed in the version 2.8. In my hundreds of hours spent using the version 2.7 I have never encountered that aforementioned bug.
However, the quest-farming bot I am working on (Angel-halo, story quests/any quest which can be favorited, extreme raids, maybe co-op leeching/slime blasting with 2 accounts, too even though this last point is actually harder to do than it may seem) will require VC++2015 redistributable packages.
