### ISSUE TITLE
The program keeps crashing

### ISSUE THREAD

**Issue by feeeeels** [Masuzu/GBFPokerBot#122]
whenever im trying to start it, it just keeps crashing.

![poker bot](https://cloud.githubusercontent.com/assets/28307110/25627280/a253856e-2f94-11e7-8d5d-735e2a9a1092.png)

**Comment by Masuzu** [comment]
Hello, it is exactly as the error message says: your Graphics card is not compatible with the minimum CUDA version required.
In any case, the CUDA version is not supported anymore and you should stop using it instead of the "regular" version:
https://github.com/Masuzu/GBFPokerBot/issues/120

On a sidenote, I wonder where people still have access to the CUDA version download link.

**Comment by feeeeels** [comment]
How long does it take to get the license? I just bought it
