### ISSUE TITLE
Can't use bot any more

### ISSUE THREAD

**Issue by Garnetus** [Masuzu/GBFPokerBot#142]
My licence is active, but the bot keep saying I'm unregistered. 
Also I tried to download the bot again from my account page but the dropbox denied all access.....is the bot dead?

**Comment by Masuzu** [comment]
Do you happen to have dropbox blocked in your country?
I can provide another download link if it is the case.

**Comment by Masuzu** [comment]
https://github.com/Masuzu/GBFPokerBot/issues/141

**Comment by kiralasani** [comment]
https://prnt.sc/fqvgt2
I am having this issue as well, dropbox is not blocked, and I have taken the steps to update the serial but it hasn't fixed the problem.

**Comment by Masuzu** [comment]
If you can download it then I am afraid that your issue is invalid.
If you follow the instructions it won't happen. Download the key file and have it in your folder. I see so many people who try to modify the contents of the key.txt. You **never have to do so**.
If your serial number file which is created when you run the bot in the same folder (serial_number.txt file) matches the one on your account management page then it *will* work.
