### ISSUE TITLE
Paid one month, but expired

### ISSUE THREAD

**Issue by lunarians** [Masuzu/GBFPokerBot#151]
Hello
Yesterday , about at 21.21 (GMT +7), I bought the one month license
And I am newly registered
now My account is expired, can you fix that please?

**Comment by Masuzu** [comment]
Hello,

Users should first use the trial period which lets you test the bot for a few hours.
Otherwise please make sure you followed the setup instruction.
https://github.com/Masuzu/GBFPokerBot/issues/146
If the licence is not extended (you can check it on your management page) then no charge were induced.
