### ISSUE TITLE
problems with the license

### ISSUE THREAD

**Issue by sentarou** [Masuzu/GBFPokerBot#161]
after upgrading to version 2.8.3 I am having problems running the application. tells me that I am an unregistered user, but I still have 7 days of leave remaining.
Screenshot http://prntscr.com/grxiuj

**Comment by Masuzu** [comment]
Hi,

Sorry for the late reply.
All licence related issues are always the same issue and due to your serial number not matching the one on your management page.
Even if this is nor specifically for the same product, the same rules apply for the poker bot as described here https://github.com/Masuzu/ZooeyBot/wiki/Setup-and-installation#first-run
