### ISSUE TITLE
OpenCV error when initiating the program

### ISSUE THREAD

**Issue by orbli** [Masuzu/GBFPokerBot#166]
![image](https://user-images.githubusercontent.com/6440599/31802232-a3184bc6-b57f-11e7-8f29-ee877db15274.png)

as title

**Comment by Masuzu** [comment]
Hi,
Scaling settings is always the cause for these issues.
Windows scaling (which users often forget to check) is not checked at start up since v2.9.0 and an error message will then be displayed.

By the way, there is no need to have the menu on the right displayed. It will only make the bot slower.

![](https://i.imgur.com/NBl7Jyw.png) is enough for instance.
