### ISSUE TITLE
Improve card selection when the hand drawn is one card away from a straight

### ISSUE THREAD

**Issue by AquaMagicks** [Masuzu/GBFPokerBot#2]
I watched the bot work on its own and noticed that it had behavioural issues; in that it would always choose pairs, but sometimes when there aren't any pairs, the selection gets a little wonky. 

List of suggestions: 

- Behaviour: include possibilities of straights. I know for sure that when the bot sees that the hand is 4/5 the same suit, it'd select it. But if there are possibilities for straights, then it would just choose one card and wipe the hand instead of selecting four cards that have a chance of straight and then move on. I can somewhat understand if it's complicated to add it (in that sometimes the chances for a straight can be a combination of a number in the middle missing, like 5/6/7/9/J), but it would be great. (And if that was the case in the first place, sorry. It just happens for me for some reason.) 
- Another way of terminating the program; while you can terminate the program by just selecting ESC, it closes the window and you can't grab the logs of the session. If there's already a place where it records the logs on termination, then make note of that in a README file. 

No other suggestions, or at least I know that I had a few, but I either forgot them, or it was clarified by rereading the notes of the options settings.

**Comment by Masuzu** [comment]
Hi AquaMagicks,

Thank you for reporting in!
When there is a single pair but 4 cards in the same suit (or a joker and 3 cards in the same suit), the bot will choose those 4 cards. As for the possibilities of straights, you are perfectly right, that is for sure something I will add in the next version to be released. Probably not before the end of the week though due to my schedule.

As for logging features and detailed statistics of the games played, that is something I will be working on after fixing the behaviour on potential straights.

**Comment by Masuzu** [comment]
Hi @AquaMagicks ,

The version 1.7.3 addresses the issue with hands one card away from a straight:
https://poker-bot.azurewebsites.net/en/Home/PatchNotes

Enjoy
