### ISSUE TITLE
Poker table hook error

### ISSUE THREAD

**Issue by shannelly2810** [Masuzu/GBFPokerBot#203]
I can't use my GBPoker Bot ver 2.9.3 because the Poker table hook error , eventhough i've done everything it asked . please help me .
![untitled](https://user-images.githubusercontent.com/39181577/39908989-dee475b8-551a-11e8-8428-d2f1d14f591d.png)

**Comment by Masuzu** [comment]
Hello,
Did you try to use Standard resolution settings:
![image](https://user-images.githubusercontent.com/5464705/40026229-d2b56a92-57d4-11e8-8f2a-54492add2dcf.png)

or to use a Medium window size instead of a large one?
![image](https://user-images.githubusercontent.com/5464705/40026246-e372e526-57d4-11e8-9bd1-63bb3ff77b09.png)

Sometimes, for some initial hand configurations, this error message may happen, but it is very rare from experience. Restarting the executable file with a different initial hand solves the issue.
Otherwise, make sure that your browser zoom is set to 100%.
There is no need to have your browser window that large, it will make the bot slower too:
![image](https://user-images.githubusercontent.com/5464705/40026317-31fefbee-57d5-11e8-8f2e-34e364bdb614.png)
is enough

**Comment by sssam2123** [comment]
Same questions. Animation settings: standard. Resolution settings: standard. Medium windows size.
Not worked. How show I solve this problem?

![image](https://user-images.githubusercontent.com/40770247/42176311-7c9e5cb2-7e63-11e8-845f-972839bf5555.png)

**Comment by sssam2123** [comment]
Solved by myself after changing monitor resolution from 1920 x 1280 to 1600 x 1200. Works will but some bugs that will recognize 8 of clubs to 6 of clubs.
