### ISSUE TITLE
I got banned from Poker Advisor via incognito mode.

### ISSUE THREAD

**Issue by Litoningu** [Masuzu/GBFPokerBot#216]
Hi! I'm new to this app and look very interesting with it so I try out and it help me a lot with my poker table time, problem is, I'm trying to play them myself for time killing and use the poker advisor to help me predict and decide to double up risk management.

By the time I start playing them were about 30 - 40 minutes in the game using incognito window from chrome to ensure no unnecessary factor effect the helper but all of sudden I got banned out of thin air.

Do my own activities be the factor of this mass ? I'm not sure if I playing too fast but I definitely sure that other than F12 window, I do not have any other add on enable other than advisor that need to activate with chrome extension.

Ban timer are mercifully at 7-8 days but sadly I have to drop all the GW farming :(

Does the poker advisor have more higher risk than the pokerbot ? 
Because I like to enjoy them myself on a freetime but now it seem that it's not as safe as it should be, please elaborate this matter to me of which one should I go for, bot or adviser ? Which one is safer ?

I regretfully accept that I might play them a little too fast like I can predict its future but I'm not sure if any other detection were involve in this matter.

**Comment by Masuzu** [comment]
Hello,
Both applications are still perfectly undetectable and have remained impervious to any of the game changes over time. Previous ban-related cases were reported only due to people botting poker for abnormally long periods of time (there has been reports of people being banned for playing Poker _manually_ for several hours in a row without interruption), and for using other game modes while botting poker (for instance joining raids and while also botting poker)
