### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by blasterion** [Masuzu/GBFPokerBot#43]
https://gyazo.com/f8f006751b22324e740f78f65d25e2ea

I got hit today I've been botting in 40 minute intervals only went maybe 4 days but still got hit =/

**Comment by tiongcock** [comment]
same here, even i got the time same as you.
yesterday works fine, but today havent got even 1 hr and then bam. got suspended.
i didnt change .ini file too

**Comment by Masuzu** [comment]
Total poker playtime over a sliding 24 hour windows should be taken into account.
Setting the debug parameter `Clicks` to true in the Debug section of the GBFpokerBot.ini file to check whether the bot does not perform more clicks due to your having a bad internet connection, outdated computer, thus forcing the bot to perform the same actions multiple time until the server registers the action, may also help you debug the issues on your own.

Such ban issue threads have already been addressed in https://github.com/Masuzu/GBFPokerBot/issues/26
Closing this one to avoid duplicates.
