### ISSUE TITLE
Poker bot CUDA ver closes on start

### ISSUE THREAD

**Issue by red-cloud0** [Masuzu/GBFPokerBot#53]
I tried running the CUDA version of the bot since the default version gives a desync message constantly and generally takes several seconds per round to identify the cards. I made sure to install the runtimes, copied key.txt over to the CUDA bot directory, and ran the exe. However, it doesn't do anything - when i run it, it pulls up the command prompt like usual, gives me the "Brought to you by Masuzu" box, then closes. My GPU is a geforce gtx 1080 which should support CUDA so i'm not sure what the issue is or what I'm missing

**Comment by Masuzu** [comment]
Hello,

You are using a GTX 1080 which uses the new "Pascal GPU" architecture. The current GBF poker bot CUDA version uses CUDA 7.5 which unfortunately won't work with Pascal GPUs.
To solve this issue, a second version of the bot needs to be recompiled using CUDA 8.0. This will probably take some time but I will work on this to support the new GeForce 10 series.

**Comment by Masuzu** [comment]
Good news, new poker bot version using CUDA 8.0 instead of CUDA 7.5 to be released by this Sunday.

**Comment by Masuzu** [comment]
Hello,

The new version labeled as 2.2.0_x64_CUDA now uses CUDA 8.0 instead of CUDA 7.5.
https://poker-bot.azurewebsites.net/en/Home/PatchNotes
https://poker-bot.azurewebsites.net/en/Manage/DownloadGBFPokerBotCUDA
I do not have a GeForce GTX 10 Series at hand so feel free to reopen the ticket should you still have some issues with it.
