### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by pokerbotissues** [Masuzu/GBFPokerBot#6]
Ever since the newest update I've gotten constant crashes and desyncs, even more than with 1.7.1. Sometimes failing to detect positions of the cards, sometimes just outright giving a message that the bot has stopped working.

**Comment by Masuzu** [comment]
I am sorry but it doesn't help at all without more data such as screenshots of the console log especially. There is a known bug with the version 1.7.2 but on good computers you should not have any desynchronization right of from the start of higher or lower in any case. It is not the expected behaviour. You might want to check the other issue topic which looks similar to this one.
As a side note I use an Intel i7 4979K
