### ISSUE TITLE
Problems with certain hands 

### ISSUE THREAD

**Issue by granblue5eva** [Masuzu/GBFPokerBot#70]
Bot works well in general, but noticed a bug with an edge case - hand combinations that are a potential flush/straight and already contain a pair. For example, a hand with 2♠ 3x 4x 5x 2♥, where x can be any suit, the bot will choose to keep the entire hand, even though it is win-less. May need some sort of statement to force it to choose between win conditions, either keeping the pair and tossing the rest or only keeping 4 cards for a straight.

**Comment by Masuzu** [comment]
Hi,

This is an unintended bug indeed. Thank you for spotting this!
I will fix this by Friday.

**Comment by Masuzu** [comment]
Actually, I am not sure I can reproduce the issue :thinking: 
Indeed, with the latest version, when you have such a hand (one away from a straight or one away from a flush with one pair), say 2♠ 3x 4x 5x 2♥ for instance, I tested and checked that only 4 out of the 5 cards will be selected.

**Comment by Masuzu** [comment]
I checked that there are no cases in which when the hand is one card away from a straight, all the cards are selected. Only 4 cards are selected.
The described situation could have happened due to a card being mistaken for another one. For instance, in the given example, '2' could have been mistaken for a '6', resulting in the bot selecting all the cards.
Should this case happen, the bot is able to detect that a mis-detection occurred and to go on "normally".
