### ISSUE TITLE
About changing the serial number

### ISSUE THREAD

**Issue by Ikaros975** [Masuzu/GBFPokerBot#75]
Hello,

I am sorry to bother you but I really need some help. I bought a one-month-licence for my friend on my computer. However, his poker bot said he was an unregistered user and asked him to update the serial number. Actually we have no idea what to do now. Could you please provide me the details how to use the licence on another computer? I really appreciate your help.

Regards,
Ikaros

**Comment by Masuzu** [comment]
Hello @Ikaros975 ,

I am really sorry for the delay. Each serial number is unique per computer and should be generated using the provided "GBF serial number generator" on the computer where you would like to run the bot.
You can change the serial number on [this page](https://poker-bot.azurewebsites.net/en/Manage/ChangeSerialNumber).
Please make sure that it matches the one generated, since the serial number can change once every four days.
Let me know if you still have trouble with this and feel free to tell your friend to drop me an email at gbfpokerbot@gmail.com if he would like a 2-day extension for the inconvenience.

Cheers
